export default [
  {name: 'Lateralus',id: 1},
  {name: 'Vicarious', id: 2},
  {name: 'Vicarious', id: 3},
  {name: 'Vicarious', id: 4},
  {name: 'Vicarious', id: 5}, 
  {name: 'Right in Two', id: 6}, 
  {name: 'Right in Two', id: 7}, 
  {name: 'Right in Two', id: 8}, 
  {name: 'Right in Two', id: 9}, 
  {name: 'Right in Two', id: 10}, 
  {name: 'Jambi', id: 11},
  {name: 'Jambi', id: 12},
  {name: 'Jambi', id: 13},
  {name: 'Jambi', id: 14},
  {name: 'Jambi', id: 15},
]
