export default [
  {name: 'Lateralus'},
  {name: 'Vicarious'},
  {name: 'Vicarious'},
  {name: 'Vicarious'},
  {name: 'Vicarious'},
  {name: 'Right in Two'}, 
  {name: 'Right in Two'}, 
  {name: 'Right in Two'}, 
  {name: 'Right in Two'}, 
  {name: 'Right in Two'}, 
  {name: 'Right in Two'}, 
  {name: 'Right in Two'}, 
  {name: 'Right in Two'}, 
  {name: 'Jambi'},
  {name: 'Jambi'},
  {name: 'Jambi'},
  {name: 'Jambi'},
  {name: 'Jambi'},
]
